name: "Snyk DotNet"
description: "Check your DotNet application for vulnerabilties using Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
  json:
    description: "Output a snyk.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://snyk/snyk:dotnet"
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }} 
