name: "Snyk Maven (3-jdk-22)"
description: "Check your Maven application for vulnerabilities using Snyk"
author: "Snyk Ltd"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
  json:
    description: "Output a snyk.json file with results if running the test command"
    default: false
runs:
  using: "docker"
  image: "docker://snyk/snyk:maven-3-jdk-22"
  env:
    FORCE_COLOR: 2
    SNYK_INTEGRATION_NAME: GITHUB_ACTIONS
    SNYK_INTEGRATION_VERSION: maven-3-jdk-22
  args:
  - snyk
  - ${{ inputs.command }}
  - ${{ inputs.args }}
