name: "Setup Snyk"
description: "Installs a specific version of Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  snyk-version:
    description: "Which Snyk version to install"
    default: latest
outputs:
  version:
    description: "The version of Snyk installed"
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/setup_snyk.sh ${{ inputs.snyk-version }} ${{ runner.os }}
      shell: bash
    - id: version
      shell: bash
      run: echo "version=$(snyk version)" >> $GITHUB_OUTPUT
