name: "Setup Snyk"
description: "Installs a specific version of Snyk"
author: "Gareth Rushgrove"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  snyk-version:
    description: "Which Snyk version to install"
    default: latest
  os:
    description: "Which Operating System Snyk will run on"
    default: ${{ runner.os }}
outputs:
  version:
    description: "The version of Snyk installed"
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Cache Snyk CLI
      id: cache-snyk
      uses: actions/cache@v4
      with:
        path: |
          /usr/local/bin/snyk
          /usr/local/bin/snyk-*
        key: snyk-${{ inputs.os }}-${{ inputs.snyk-version }}

    - name: Install Snyk CLI
      if: inputs.snyk-version == 'latest' || steps.cache-snyk.outputs.cache-hit != 'true'
      shell: bash
      env:
        INPUT_SNYK_VERSION: ${{ inputs.snyk-version }}
        INPUT_OS: ${{ inputs.os }}
      run: |
        ${{ github.action_path }}/setup_snyk.sh "${INPUT_SNYK_VERSION}" "${INPUT_OS}" || $GITHUB_ACTION_PATH/setup_snyk.sh "${INPUT_SNYK_VERSION}" "${INPUT_OS}"

    - name: Get Snyk version
      id: version
      shell: bash
      run: echo "version=$(snyk version)" >> "${GITHUB_OUTPUT}"
